version: '3.8'

services:
  web:
    build: .
    ports:
      - "4567:4567"
    volumes:
      - db_data:/app
    environment:
      - RACK_ENV=production
      - SINATRA_ENV=production
    restart: unless-stopped

volumes:
  db_data: