version: "3.9"

services:
  web:
    container_name: cicd-web
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    restart: always
    networks:
      - cicd-net

  nginx:
    container_name: cicd-nginx
    image: nginx:1.27-alpine
    depends_on:
      - web
    ports:
      - "80:80"
      # - "443:443" # enable if you add TLS certs and update the config
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always
    networks:
      - cicd-net

networks:
  cicd-net:
    driver: bridge