version: '3.8'

services:
  web:
    build: .
    ports:
      - "4567:4567"
    volumes:
      - .:/app
      - db_data:/app/db
    environment:
      - RACK_ENV=production
      - SINATRA_ENV=production
    restart: unless-stopped
    command: puma -p 4567 app.rb

volumes:
  db_data: