source "https://rubygems.org"

git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "~> 3.3"

gem "rails", "~> 7.1"
gem "sqlite3", "~> 1.6"
gem "puma", "~> 6.4"
gem "rack-cors", "~> 2.0"

group :development, :test do
  gem "dotenv-rails", "~> 3.0"
end